FROM node:latest

# Working directory
WORKDIR /usr/src/app

# I know this is supposed to be after npm install but for whatever reason vite doesn't get installed if I do that

# Copy package.json and package-lock.json
COPY package*.json ./
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/

# Install dependencies
RUN npm install

# Copy source code
COPY . .

CMD chmod +x /usr/src/app/docker/server/entry.dev.sh

CMD ln /usr/src/app/backend/config.dev.js /usr/src/app/backend/config.js 
# we ln it, but this will be removed once the container actually starts, will be recreated by the entry.dev.sh script

# Expose ports
EXPOSE 3000
EXPOSE 5173

# Run the server
CMD /usr/src/app/docker/server/entry.dev.sh