version: "3.8"
services:
  server:
    build: 
      context: "."
      dockerfile: "./docker/server/Dockerfile"
      args:
        DEVELOPMENT: ${DEVELOPMENT}
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app/backend
      - type: bind
        source: ./frontend
        target: /usr/src/app/frontend
    ports:
      - "3000:3000"
      - "5173:5173"
  db:
    build: 
      context: "."
      dockerfile: "./docker/db/Dockerfile"
    restart: always
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080