services:
  server:
    build:
      context: "."
      dockerfile: "./docker/server/Dockerfile"
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    stop_grace_period: 1s
  db:
    build:
      context: "."
      dockerfile: "./docker/db/Dockerfile"
    restart: always
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
